Algoritmo "Medidas"

Var

a, b, c, areaA, areaAB, areaABC : real



Inicio

escreva ("Digite a medida de A: ")
leia (a)
escreva ("Digite a medida de B: ")
leia (b)
escreva ("Digite a medida de C: ")
leia (c)

areaA <- a * a
escreval ("AREA DO QUADRADO = ", areaA:8:4 )

areaAB <- a * b /2
escreval ("AREA DO TRIANGULO = ", areaAB:8:4)

areaABC <- ((a + b) * c) / 2
escreval ("AREA DO TRAPEZIO = ", areaABC:8:4)

Fimalgoritmo